// app/layout.jsx
import {NextIntlClientProvider} from 'next-intl';
import {getLocale, getMessages} from 'next-intl/server'; 
import { Toaster } from "@/components/ui/sonner"
import { Inter } from "next/font/google";
import Providers from "@/context/providers";
import CookieConsentComponent from "@/components/cookie-consent";
import ScrollToTop from '@/components/scroll-to-top';
import "@/app/globals.css";

const font = Inter({
    subsets: ["latin"]
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport = {
    viewport: "user-scalable=0, initial-scale=1, minimum-scale=1, maximum-scale=1, width=device-width",
}

export default async function RootLayout({ children }) {
    const locale = await getLocale();
    const messages = await getMessages();

    return (
        <html lang={locale}>
        <body className={font.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
            <Providers>
                <Toaster position="top-center" />
                <ScrollToTop />
                    {children}
                <CookieConsentComponent />
            </Providers>
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
